"""fix_data_text_type

Revision ID: 63a6e0d64feb
Revises: cce7bfd2d03d
Create Date: 2020-10-29 19:34:05.126565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a6e0d64feb'
down_revision = 'cce7bfd2d03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.alter_column('input_header',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('input_para',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('output_para',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('response',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('output_para',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('input_para',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('input_header',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
