"""dev-add-report

Revision ID: 9e06476a7e15
Revises: e424b564e8c5
Create Date: 2021-01-25 11:34:47.715008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e06476a7e15'
down_revision = 'e424b564e8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casestatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_num', sa.Integer(), nullable=True),
    sa.Column('case_num', sa.Integer(), nullable=True),
    sa.Column('run_case_num', sa.Integer(), nullable=True),
    sa.Column('success_case_num', sa.Integer(), nullable=True),
    sa.Column('failure_case_num', sa.Integer(), nullable=True),
    sa.Column('exception_case_num', sa.Integer(), nullable=True),
    sa.Column('today_run_case_num', sa.Integer(), nullable=True),
    sa.Column('today_suc_case_num', sa.Integer(), nullable=True),
    sa.Column('today_fail_case_num', sa.Integer(), nullable=True),
    sa.Column('today_exc_case_num', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.String(length=16), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品id'),
    sa.Column('module_id', sa.Integer(), nullable=False, comment='模块id'),
    sa.Column('day_date', sa.String(length=64), nullable=False, comment='日期'),
    sa.Column('total_num', sa.Integer(), nullable=True, comment='总数'),
    sa.Column('open_num', sa.Integer(), nullable=True, comment='开启状态的数量'),
    sa.Column('closed_num', sa.Integer(), nullable=True, comment='关闭状态的数量'),
    sa.Column('resolve_num', sa.Integer(), nullable=True, comment='解决的数量'),
    sa.Column('crash_num', sa.Integer(), nullable=True, comment='崩溃bug数量 severity:1'),
    sa.Column('block_num', sa.Integer(), nullable=True, comment='阻断bug数量 severity:2'),
    sa.Column('serious_num', sa.Integer(), nullable=True, comment='严重bug数量 severity:3'),
    sa.Column('sort_num', sa.Integer(), nullable=True, comment='一般bug数量 severity:4'),
    sa.Column('propose_num', sa.Integer(), nullable=True, comment='建议bug数量 severity:5'),
    sa.Column('risks', sa.Text(), nullable=True, comment='风险'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品id'),
    sa.Column('product_name', sa.String(length=128), nullable=False, comment='产品名称'),
    sa.Column('product_status', sa.Integer(), nullable=False, comment='产品状态 0未提测、1测试中、2测试完成 '),
    sa.Column('module_id', sa.Integer(), nullable=False, comment='模块id'),
    sa.Column('module_name', sa.String(length=128), nullable=False, comment='模块名称'),
    sa.Column('start_day', sa.String(length=128), nullable=True, comment='统计开始日期'),
    sa.Column('end_day', sa.String(length=128), nullable=True, comment='统计结束日期'),
    sa.Column('module_status', sa.Integer(), nullable=False, comment='模块状态 0未提测、1测试中、2测试完成 '),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='产品id'),
    sa.Column('module_id', sa.Integer(), nullable=False, comment='模块id'),
    sa.Column('day_date', sa.String(length=64), nullable=True, comment='日期'),
    sa.Column('user_name', sa.String(length=64), nullable=True, comment='人员姓名'),
    sa.Column('total_num', sa.Integer(), nullable=False, comment='名下总数量'),
    sa.Column('open_num', sa.Integer(), nullable=True, comment='开启状态的数量'),
    sa.Column('resolve_num', sa.Integer(), nullable=True, comment='解决的数量'),
    sa.Column('closed_num', sa.Integer(), nullable=True, comment='解决的数量'),
    sa.Column('user_type', sa.Integer(), nullable=False, comment='用户类型 0创建人 1解决人 2关闭人'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aksk_header', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('input_header', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('input_para', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_para', sa.Text(), nullable=True))
        batch_op.alter_column('diff_res',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('res_assert',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('db_host',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.alter_column('default',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('param_desc',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('report_copy',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('report_to',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('run_time',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('task_make_email',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ak', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('has_input', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_output', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_sign', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('input_header', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('input_para', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('output_para', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sk', sa.String(length=64), nullable=True))
        batch_op.alter_column('field_value',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('res_assert',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('sql',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.alter_column('sql',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('res_assert',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('field_value',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('sk')
        batch_op.drop_column('output_para')
        batch_op.drop_column('input_para')
        batch_op.drop_column('input_header')
        batch_op.drop_column('has_sign')
        batch_op.drop_column('has_output')
        batch_op.drop_column('has_input')
        batch_op.drop_column('ak')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task_make_email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('run_time',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('report_to',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('report_copy',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.alter_column('param_desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('default',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('interfaces', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('db_host',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('res_assert',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('params',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('header',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('diff_res',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('output_para')
        batch_op.drop_column('input_para')
        batch_op.drop_column('input_header')
        batch_op.drop_column('aksk_header')

    op.drop_table('report_user')
    op.drop_table('report_product')
    op.drop_table('report_day')
    op.drop_table('casestatistics')
    # ### end Alembic commands ###
