"""add_input_and_output_para

Revision ID: cce7bfd2d03d
Revises: 4aabe4180e9b
Create Date: 2020-10-28 19:13:21.571904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce7bfd2d03d'
down_revision = '4aabe4180e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_header', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('input_para', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('output_para', sa.String(length=64), nullable=True))

    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_input', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_output', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('input_header', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('input_para', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('output_para', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.drop_column('output_para')
        batch_op.drop_column('input_para')
        batch_op.drop_column('input_header')
        batch_op.drop_column('has_output')
        batch_op.drop_column('has_input')

    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.drop_column('output_para')
        batch_op.drop_column('input_para')
        batch_op.drop_column('input_header')

    # ### end Alembic commands ###
