"""add_aksk_sign

Revision ID: dce12f5f356d
Revises: ffe2123d32ee
Create Date: 2020-11-09 20:43:50.853895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce12f5f356d'
down_revision = 'ffe2123d32ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aksk_header', sa.Text(), nullable=True))

    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ak', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('has_sign', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sk', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testcases', schema=None) as batch_op:
        batch_op.drop_column('sk')
        batch_op.drop_column('has_sign')
        batch_op.drop_column('ak')

    with op.batch_alter_table('caseresults', schema=None) as batch_op:
        batch_op.drop_column('aksk_header')

    # ### end Alembic commands ###
