"""add_case_

Revision ID: e424b564e8c5
Revises: dce12f5f356d
Create Date: 2020-11-24 20:59:46.897256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e424b564e8c5'
down_revision = 'dce12f5f356d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casestatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_num', sa.Integer(), nullable=True),
    sa.Column('case_num', sa.Integer(), nullable=True),
    sa.Column('run_case_num', sa.Integer(), nullable=True),
    sa.Column('success_case_num', sa.Integer(), nullable=True),
    sa.Column('failure_case_num', sa.Integer(), nullable=True),
    sa.Column('exception_case_num', sa.Integer(), nullable=True),
    sa.Column('today_run_case_num', sa.Integer(), nullable=True),
    sa.Column('today_suc_case_num', sa.Integer(), nullable=True),
    sa.Column('today_fail_case_num', sa.Integer(), nullable=True),
    sa.Column('today_exc_case_num', sa.Integer(), nullable=True),
    sa.Column('open_date', sa.String(length=16), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casestatistics')
    # ### end Alembic commands ###
